CREATE TABLE [dbo].[Yearly_Report] (
    [YR_ID]           INT             IDENTITY (1, 1) NOT NULL,
    [YR_Year]         INT             NOT NULL,
    [YR_CID]          INT             NOT NULL,
    [YR_DateSaved]    DATETIME        NULL,
    [YR_DateSent]     DATETIME        NULL,
    [YR_Sent]         SMALLINT        NULL,
    [YR_Modif]        SMALLINT        NULL,
    [YR_DateSentPrev] DATETIME        NULL,
    [YR_Final]        SMALLINT        NOT NULL,
    [YR_Comments]     TEXT            NULL,
    [YR_WeightA1]     DECIMAL (18, 6) DEFAULT ((0)) NULL,
    [YR_WeightA2]     DECIMAL (18, 6) NULL,
    [YR_WeightA3]     DECIMAL (18, 6) DEFAULT ((0)) NULL,
    [YR_WeightA4]     DECIMAL (18, 6) NULL,
    [YR_WeightA5]     DECIMAL (18, 6) NULL,
    [YR_WeightA6]     DECIMAL (18, 6) NULL,
    [YR_WeightA7]     DECIMAL (18, 6) NULL,
    [YR_WeightA8]     DECIMAL (18, 6) DEFAULT ((0)) NULL,
    [YR_WeightA9]     DECIMAL (18, 6) NULL,
    [YR_WeightA10]    DECIMAL (18, 6) NULL,
    [YR_WeightA11]    DECIMAL (18, 6) NULL,
    [YR_WeightA12]    DECIMAL (18, 6) NULL,
    [YR_WeightA13]    DECIMAL (18, 6) NULL,
    [YR_WeightA14]    DECIMAL (18, 6) NULL,
    [YR_WeightA15]    DECIMAL (18, 6) NULL,
    [YR_WeightA16]    DECIMAL (18, 6) NULL,
    [YR_WeightA17]    DECIMAL (18, 6) NULL,
    [YR_WeightA18]    DECIMAL (18, 6) NULL,
    [YR_WeightA19]    DECIMAL (18, 6) NULL,
    [YR_WeightA20]    DECIMAL (18, 6) NULL,
    [YR_WeightA21]    DECIMAL (18, 6) NULL,
    [YR_WeightA22]    DECIMAL (18, 6) NULL,
    [YR_WeightA23]    DECIMAL (18, 6) NULL,
    [YR_WeightA24]    DECIMAL (18, 6) NULL,
    [YR_WeightA25]    DECIMAL (18, 6) NULL,
    [YR_WeightA26]    DECIMAL (18, 6) NULL,
    [YR_WeightA27]    DECIMAL (18, 6) NULL,
    [YR_WeightA28]    DECIMAL (18, 6) NULL,
    [YR_WeightA29]    DECIMAL (18, 6) NULL,
    [YR_WeightA30]    DECIMAL (18, 6) NULL,
    [YR_WeightA31]    DECIMAL (18, 6) NULL,
    [YR_WeightA32]    DECIMAL (18, 6) NULL,
    [YR_WeightA33]    DECIMAL (18, 6) NULL,
    [YR_WeightA34]    DECIMAL (18, 6) NULL,
    [YR_WeightA35]    DECIMAL (18, 6) NULL,
    [YR_WeightA36]    DECIMAL (18, 6) NULL,
    [YR_WeightA37]    DECIMAL (18, 6) NULL,
    [YR_WeightA38]    DECIMAL (18, 6) NULL,
    [YR_WeightA39]    DECIMAL (18, 6) NULL,
    [YR_WeightA40]    DECIMAL (18, 6) NULL,
    [YR_WeightA41]    DECIMAL (18, 6) NULL,
    [YR_WeightA42]    DECIMAL (18, 6) NULL,
    [YR_WeightA43]    DECIMAL (18, 6) NULL,
    [YR_WeightA44]    DECIMAL (18, 6) NULL,
    [YR_WeightA45]    DECIMAL (18, 6) NULL,
    [YR_WeightA46]    DECIMAL (18, 6) NULL,
    [YR_WeightA47]    DECIMAL (18, 6) NULL,
    [YR_WeightA48]    DECIMAL (18, 6) NULL,
    [YR_WeightA49]    DECIMAL (18, 6) NULL,
    [YR_WeightA50]    DECIMAL (18, 6) NULL,
    [YR_WeightA51]    DECIMAL (18, 6) NULL,
    [YR_WeightA52]    DECIMAL (18, 6) NULL,
    [YR_WeightA53]    DECIMAL (18, 6) NULL,
    [YR_WeightA54]    DECIMAL (18, 6) NULL,
    [YR_WeightA55]    DECIMAL (18, 6) NULL,
    [YR_WeightA56]    DECIMAL (18, 6) NULL,
    [YR_WeightA57]    DECIMAL (18, 6) NULL,
    [YR_WeightA58]    DECIMAL (18, 6) NULL,
    [YR_WeightA59]    DECIMAL (18, 6) NULL,
    [YR_WeightA60]    DECIMAL (18, 6) NULL,
    [YR_WeightA61]    DECIMAL (18, 6) NULL,
    [YR_WeightA62]    DECIMAL (18, 6) NULL,
    [YR_WeightA63]    DECIMAL (18, 6) NULL,
    [YR_WeightA64]    DECIMAL (18, 6) NULL,
    [YR_WeightA65]    DECIMAL (18, 6) NULL,
    [YR_WeightA66]    DECIMAL (18, 6) NULL,
    [YR_WeightA67]    DECIMAL (18, 6) NULL,
    [YR_WeightA68]    DECIMAL (18, 6) NULL,
    [YR_ContribA1]    DECIMAL (15, 2) DEFAULT ((0)) NULL,
    [YR_ContribA2]    DECIMAL (15, 2) NULL,
    [YR_ContribA3]    DECIMAL (15, 2) DEFAULT ((0)) NULL,
    [YR_ContribA4]    DECIMAL (15, 2) NULL,
    [YR_ContribA5]    DECIMAL (15, 2) NULL,
    [YR_ContribA6]    DECIMAL (15, 2) NULL,
    [YR_ContribA7]    DECIMAL (15, 2) NULL,
    [YR_ContribA8]    DECIMAL (15, 2) DEFAULT ((0)) NULL,
    [YR_ContribA9]    DECIMAL (15, 2) NULL,
    [YR_ContribA10]   DECIMAL (15, 2) NULL,
    [YR_ContribA11]   DECIMAL (15, 2) NULL,
    [YR_ContribA12]   DECIMAL (15, 2) NULL,
    [YR_ContribA13]   DECIMAL (15, 2) NULL,
    [YR_ContribA14]   DECIMAL (15, 2) NULL,
    [YR_ContribA15]   DECIMAL (15, 2) NULL,
    [YR_ContribA16]   DECIMAL (15, 2) NULL,
    [YR_ContribA17]   DECIMAL (15, 2) NULL,
    [YR_ContribA18]   DECIMAL (15, 2) NULL,
    [YR_ContribA19]   DECIMAL (15, 2) NULL,
    [YR_ContribA20]   DECIMAL (15, 2) NULL,
    [YR_ContribA21]   DECIMAL (15, 2) NULL,
    [YR_ContribA22]   DECIMAL (15, 2) NULL,
    [YR_ContribA23]   DECIMAL (15, 2) NULL,
    [YR_WeightB]      DECIMAL (15, 2) NULL,
    [YR_ContribB]     DECIMAL (15, 4) NULL,
    [YR_WeightC]      DECIMAL (15, 2) NULL,
    [YR_ContribC]     DECIMAL (15, 2) NULL,
    [YR_Manual]       SMALLINT        NOT NULL,
    [YR_ChkSymet1]    SMALLINT        NULL,
    [YR_ChkSymet2]    SMALLINT        NULL,
    [YR_ChkSymet3]    SMALLINT        NULL,
    [YR_SenderName]   VARCHAR (255)   NULL,
    [YR_Form2021]     SMALLINT        DEFAULT ((0)) NOT NULL,
    [YR_OneUse]       DECIMAL (15, 2) DEFAULT ((0)) NULL,
    [YR_MultiUse]     DECIMAL (15, 2) DEFAULT ((0)) NULL,
    [YR_PrimaryTem]   DECIMAL (15, 2) DEFAULT ((0)) NULL,
    [YR_SecondaryTem] DECIMAL (15, 2) DEFAULT ((0)) NULL,
    [YR_WeightB2]     DECIMAL (18, 6) DEFAULT ((0)) NULL,
    [YR_WeightB4]     DECIMAL (18, 6) DEFAULT ((0)) NULL,
    [YR_WeightB5]     DECIMAL (18, 6) DEFAULT ((0)) NULL,
    [YR_WeightB6]     DECIMAL (18, 6) DEFAULT ((0)) NULL,
    [YR_WeightB7]     DECIMAL (18, 6) DEFAULT ((0)) NULL,
    [YR_WeightB9]     DECIMAL (18, 6) DEFAULT ((0)) NULL,
    [YR_WeightB10]    DECIMAL (18, 6) DEFAULT ((0)) NULL,
    [YR_WeightB11]    DECIMAL (18, 6) DEFAULT ((0)) NULL,
    [YR_WeightB14]    DECIMAL (18, 6) DEFAULT ((0)) NULL,
    [YR_WeightB15]    DECIMAL (18, 6) DEFAULT ((0)) NULL,
    [YR_WeightB16]    DECIMAL (18, 6) DEFAULT ((0)) NULL,
    [YR_WeightB17]    DECIMAL (18, 6) DEFAULT ((0)) NULL,
    [YR_WeightB18]    DECIMAL (18, 6) DEFAULT ((0)) NULL,
    [YR_WeightB19]    DECIMAL (18, 6) DEFAULT ((0)) NULL,
    [YR_WeightB20]    DECIMAL (18, 6) DEFAULT ((0)) NULL,
    [YR_WeightB21]    DECIMAL (18, 6) DEFAULT ((0)) NULL,
    [YR_WeightB22]    DECIMAL (18, 6) DEFAULT ((0)) NULL,
    [YR_WeightB23]    DECIMAL (18, 6) DEFAULT ((0)) NULL,
    [YR_WeightA69]    DECIMAL (18, 6) NULL,
    [YR_WeightA70]    DECIMAL (18, 6) NULL,
    [YR_WeightA71]    DECIMAL (18, 6) NULL,
    [YR_WeightA72]    DECIMAL (18, 6) NULL,
    [YR_WeightA73]    DECIMAL (18, 6) NULL,
    [YR_WeightA74]    DECIMAL (18, 6) NULL,
    [YR_WeightA75]    DECIMAL (18, 6) NULL,
    [YR_WeightA76]    DECIMAL (18, 6) NULL,
    [YR_WeightA77]    DECIMAL (18, 6) NULL,
    [YR_WeightA78]    DECIMAL (18, 6) NULL,
    [YR_WeightA79]    DECIMAL (18, 6) NULL,
    [YR_WeightA80]    DECIMAL (18, 6) NULL,
    [YR_WeightA81]    DECIMAL (18, 6) NULL,
    [YR_WeightA82]    DECIMAL (18, 6) NULL,
    [YR_WeightA83]    DECIMAL (18, 6) NULL,
    [YR_WeightA84]    DECIMAL (18, 6) NULL,
    [YR_WeightA85]    DECIMAL (18, 6) NULL,
    [YR_WeightA86]    DECIMAL (18, 6) NULL,
    [YR_WeightA87]    DECIMAL (18, 6) NULL,
    [YR_WeightA88]    DECIMAL (18, 6) NULL,
    [YR_WeightA89]    DECIMAL (18, 6) NULL,
    [YR_WeightA90]    DECIMAL (18, 6) NULL,
    [YR_WeightA91]    DECIMAL (18, 6) NULL,
    [YR_WeightA92]    DECIMAL (18, 6) NULL,
    [YR_WeightA93]    DECIMAL (18, 6) NULL,
    [YR_WeightA94]    DECIMAL (18, 6) NULL,
    [YR_WeightA95]    DECIMAL (18, 6) NULL,
    [YR_WeightA96]    DECIMAL (18, 6) NULL,
    [YR_WeightA97]    DECIMAL (18, 6) NULL,
    [YR_WeightA98]    DECIMAL (18, 6) NULL,
    [YR_WeightA99]    DECIMAL (18, 6) NULL,
    [YR_WeightA100]   DECIMAL (18, 6) NULL,
    [YR_WeightA101]   DECIMAL (18, 6) NULL,
    [YR_WeightA102]   DECIMAL (18, 6) NULL,
    [YR_WeightA103]   DECIMAL (18, 6) NULL,
    [YR_WeightB30]    DECIMAL (18, 6) NULL,
    [YR_WeightB31]    DECIMAL (18, 6) NULL,
    [YR_WeightB33]    DECIMAL (18, 6) NULL,
    [YR_WeightB37]    DECIMAL (18, 6) NULL,
    [YR_WeightB38]    DECIMAL (18, 6) NULL,
    [YR_WeightB40]    DECIMAL (18, 6) NULL,
    [YR_WeightB44]    DECIMAL (18, 6) NULL,
    [YR_WeightB45]    DECIMAL (18, 6) NULL,
    [YR_WeightB47]    DECIMAL (18, 6) NULL,
    [YR_WeightB48]    DECIMAL (18, 6) NULL,
    [YR_WeightB49]    DECIMAL (18, 6) NULL,
    [YR_WeightB51]    DECIMAL (18, 6) NULL,
    [YR_WeightB52]    DECIMAL (18, 6) NULL,
    [YR_WeightB53]    DECIMAL (18, 6) NULL,
    [YR_WeightB55]    DECIMAL (18, 6) NULL,
    [YR_WeightB56]    DECIMAL (18, 6) NULL,
    [YR_WeightB57]    DECIMAL (18, 6) NULL,
    [YR_WeightB58]    DECIMAL (18, 6) NULL,
    [YR_WeightB60]    DECIMAL (18, 6) NULL,
    [YR_WeightB61]    DECIMAL (18, 6) NULL,
    [YR_WeightB62]    DECIMAL (18, 6) NULL,
    [YR_WeightB63]    DECIMAL (18, 6) NULL,
    [YR_WeightB64]    DECIMAL (18, 6) NULL,
    [YR_WeightB65]    DECIMAL (18, 6) NULL,
    [YR_WeightB66]    DECIMAL (18, 6) NULL,
    [YR_WeightB67]    DECIMAL (18, 6) NULL,
    [YR_WeightB68]    DECIMAL (18, 6) NULL,
    [YR_WeightB69]    DECIMAL (18, 6) NULL,
    [YR_WeightB70]    DECIMAL (18, 6) NULL,
    [YR_WeightB71]    DECIMAL (18, 6) NULL,
    [YR_WeightB72]    DECIMAL (18, 6) NULL,
    [YR_WeightB73]    DECIMAL (18, 6) NULL,
    [YR_WeightB74]    DECIMAL (18, 6) NULL,
    [YR_WeightB75]    DECIMAL (18, 6) NULL,
    [YR_WeightB76]    DECIMAL (18, 6) NULL,
    [YR_WeightB77]    DECIMAL (18, 6) NULL,
    [YR_WeightB78]    DECIMAL (18, 6) NULL,
    [YR_WeightB79]    DECIMAL (18, 6) NULL,
    [YR_WeightB80]    DECIMAL (18, 6) NULL,
    [YR_WeightB81]    DECIMAL (18, 6) NULL,
    [YR_WeightB82]    DECIMAL (18, 6) NULL,
    [YR_WeightB83]    DECIMAL (18, 6) NULL,
    [YR_WeightB84]    DECIMAL (18, 6) NULL,
    [YR_WeightB85]    DECIMAL (18, 6) NULL,
    [YR_WeightB86]    DECIMAL (18, 6) NULL,
    [YR_WeightB87]    DECIMAL (18, 6) NULL,
    [YR_WeightB88]    DECIMAL (18, 6) NULL,
    [YR_WeightB90]    DECIMAL (18, 6) NULL,
    [YR_WeightB92]    DECIMAL (18, 6) NULL,
    [YR_WeightB94]    DECIMAL (18, 6) NULL,
    [YR_WeightB96]    DECIMAL (18, 6) NULL,
    [YR_WeightB98]    DECIMAL (18, 6) NULL,
    [YR_WeightB100]   DECIMAL (18, 6) NULL,
    [YR_WeightB102]   DECIMAL (18, 6) NULL,
    CONSTRAINT [PK_Yearly_Report] PRIMARY KEY CLUSTERED ([YR_ID] ASC)
);
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_YR_Unique]
    ON [dbo].[Yearly_Report]([YR_Year] ASC, [YR_CID] ASC, [YR_Final] ASC, [YR_Modif] ASC);
GO
